### PR TITLE
All updates needed to deploy root site to new infrastructure

### PR DESCRIPTION
**Pull request by eefahy**
This is needed to test a full deployment cycle to the new environment. Once QA is complete I will make another PR to update the default webprefix for a prod deploy.

### CODE REVIEW

**Comment by srabun** [comment]
this all looks good to me

**Comment by srabun** [comment]
I've added a few things to the site, should we add those in before merging? @eefahy

**Comment by zimeon** [comment]
From a scan through this seems OK to me as rework of the non-`/api` non-`/model` pages. Should the files under `/model` also be removed?

**Comment by glenrobson** [comment]
Please use pull request #3 as it includes these changes and also removes the model.

**Comment by eefahy** [comment]
ok I pulled in @glenrobson's changes here and rebased with master at iiif.io repo

**Comment by mikeapp** [comment]
👍

**Pull request merged**
